// ServerControl.swift - UI-side wrapper around the iosspectd daemon.
//
// The app does not host the server itself. The daemon (iosspectd) is a
// separate binary installed at /var/jb/usr/local/bin/iosspectd and
// loaded by launchd at boot via the LaunchDaemons plist (KeepAlive=true).
// This wrapper sends commands to it and surfaces the runtime state
// (URL, fingerprint, password, last error) to SwiftUI.
//
// Split rationale:
//   - The app process exits when the user backgrounds it.
//   - launchd-managed daemons survive backgrounding.
//   - The daemon needs root for /var/mobile reads; the .app stays a
//     normal UI process for minimal attack surface.
//
// File-poll control channel instead of launchctl:
//   - The daemon runs as root via launchd; the SwiftUI app runs as
//     mobile (uid 501). iOS won't let a mobile-uid process bootout a
//     root-owned service even when it's visible in user/501.
//   - Start/Stop/Restart all work by dropping a line into a file the
//     daemon polls every second. The daemon reacts as root; the UI
//     refresh timer reads the daemon's state file ~2s later.

import Foundation
import Combine
import UIKit
import Darwin

@MainActor
final class ServerControl: ObservableObject {
    static let shared = ServerControl()

    @Published var isRunning: Bool = false
    @Published var lastError: String? = nil

    // Live state. Mirrored from disk on every refresh so manual edits
    // outside the app still update the dashboard.
    @Published var url: String? = nil
    @Published var fingerprintShort: String = "-"
    @Published var password: String = "-"
    @Published var deviceWord: String = "jailbroken"

    private var poll: Timer?

    private init() {
        refresh()
        // Use the singleton inside the Task so we avoid the "captured
        // mutable self in concurrent context" error under strict
        // concurrency. Holding the timer strong is fine - the singleton
        // lives for the app's lifetime anyway.
        poll = Timer.scheduledTimer(withTimeInterval: 2.0, repeats: true) { _ in
            Task { @MainActor in
                ServerControl.shared.refresh()
            }
        }
    }

    // MARK: - First launch

    func bootstrapIfNeeded() {
        // Settings.password is lazily generated on first read.
        _ = Settings.shared.password
        // Cert is generated by the daemon at first start, not here.
    }

    // MARK: - Control commands
    //
    // Each writes a single line to /var/mobile/Library/IOSspect/control.
    // The daemon polls that file once a second, executes the command,
    // then deletes the file. Our refresh timer (2s) picks up the new
    // daemon-side state from /var/mobile/Library/IOSspect/state.

    func start()   { send("start",   optimistic: true) }
    func stop()    { send("stop",    optimistic: false) }
    func restart() { send("restart", optimistic: false) }

    private func send(_ cmd: String, optimistic: Bool) {
        lastError = nil
        let path = "/var/mobile/Library/IOSspect/control"
        do {
            try cmd.write(toFile: path, atomically: true, encoding: .utf8)
        } catch {
            lastError = "Couldn't write control file: \(error.localizedDescription)"
            return
        }
        // Optimistically flip the UI so the button visibly reacts even
        // before the daemon's state file catches up.
        isRunning = optimistic
        DispatchQueue.main.asyncAfter(deadline: .now() + 3) { [weak self] in
            self?.refresh()
        }
    }

    // MARK: - Password

    func regeneratePassword() {
        Settings.shared.regeneratePassword()
        // Daemon needs to pick up the new password. Full restart so the
        // new value gets baked into SharedSettings.load() on next boot.
        if isRunning { restart() }
        refresh()
    }

    // MARK: - Refresh state

    private func refresh() {
        isRunning = (readState() == "running")
        password = Settings.shared.password
        let port = Settings.shared.port
        if let ip = NetworkUtil.primaryIPv4() {
            url = "https://\(ip):\(port)"
        } else {
            url = "https://127.0.0.1:\(port)"
        }
        // Fingerprint is whatever the daemon wrote out at last start. The
        // daemon stores it at /var/mobile/Library/IOSspect/cert.fingerprint.
        if let fp = try? String(contentsOfFile: CertPaths.fingerprintFile, encoding: .utf8) {
            fingerprintShort = fp.trimmingCharacters(in: .whitespacesAndNewlines)
        } else {
            fingerprintShort = "(start the server)"
        }
    }

    private func readState() -> String {
        let path = "/var/mobile/Library/IOSspect/state"
        guard let s = try? String(contentsOfFile: path, encoding: .utf8) else {
            // No state file yet => daemon never wrote one => treat as
            // "not started". Avoids a misleading green dot on first launch
            // before the daemon has had a chance to claim running state.
            return "stopped"
        }
        return s.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
    }
}

enum CertPaths {
    static var dir: String {
        let base = FileManager.default.urls(for: .libraryDirectory, in: .userDomainMask).first?.path
            ?? "/var/mobile/Library"
        return "\(base)/IOSspect"
    }
    static var fingerprintFile: String { "\(dir)/cert.fingerprint" }
}
